const fetchProducts = async (query) => {
    // Simulação de dados de produtos com base na categoria (query)
    const produtosMock = {
        computador: [
            {
                id: "1",
                name: "Notebook Gamer X1",
                description: "Notebook com processador Intel i7, 16GB de RAM, e placa de vídeo dedicada.",
                price: 5999.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "2",
                name: "Computador All-in-One A3",
                description: "Computador completo com tela de 23 polegadas, ideal para escritórios e home-office.",
                price: 2999.99,
                image: "/imagens/computador.png",
            },
            {
                id: "3",
                name: "PC Desktop SpeedPro",
                description: "PC gamer com processador Ryzen 7, 32GB de RAM e placa de vídeo RTX 3060.",
                price: 7999.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "4",
                name: "Mini PC S10",
                description: "Mini PC compacto com bom desempenho para tarefas do dia a dia.",
                price: 1999.99,
                image: "/imagens/computador.png",
            },
            {
                id: "5",
                name: "Notebook Ultrafino Lumen",
                description: "Ultrafino com SSD de 512GB, ideal para produtividade e mobilidade.",
                price: 4299.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "6",
                name: "Desktop Office Prime",
                description: "Computador para escritório com ótimo desempenho em tarefas administrativas.",
                price: 2599.00,
                image: "/imagens/computador.png",
            },
            {
                id: "7",
                name: "Notebook Pro Studio",
                description: "Modelo voltado para edições de vídeo e uso de softwares pesados.",
                price: 8899.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "8",
                name: "Desktop Gamer Firestorm",
                description: "Configuração ideal para jogos de última geração em alta resolução.",
                price: 9499.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "9",
                name: "All-in-One Touchscreen Vivid",
                description: "Modelo com tela sensível ao toque, ótimo para uso em ambientes educacionais.",
                price: 3199.99,
                image: "/imagens/computador.png",
            },
            {
                id: "10",
                name: "Notebook EcoLite",
                description: "Leve e econômico, com foco em atividades simples do dia a dia.",
                price: 1899.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "11",
                name: "Mini PC Pro Box",
                description: "Compacto e poderoso, ideal para espaços pequenos.",
                price: 2399.99,
                image: "/imagens/computador.png",
            },
            {
                id: "12",
                name: "Notebook Creator Max",
                description: "Feito para criadores de conteúdo, com tela Full HD e ótimo processamento gráfico.",
                price: 6999.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "13",
                name: "Desktop Home Smart",
                description: "Desempenho suficiente para tarefas domésticas e navegação.",
                price: 2099.99,
                image: "/imagens/computador.png",
            },
            {
                id: "14",
                name: "Notebook Ultra X14",
                description: "Design elegante com hardware de ponta para quem exige performance.",
                price: 7999.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "15",
                name: "Desktop TurboPower",
                description: "Alto desempenho para multitarefa, ideal para empresas.",
                price: 6499.99,
                image: "/imagens/computador.png",
            },
            {
                id: "16",
                name: "Notebook Estudantil Basic",
                description: "Modelo acessível para estudos e navegação simples.",
                price: 1499.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "17",
                name: "PC Gamer Overdrive",
                description: "Máquina potente com foco total em jogos AAA.",
                price: 9999.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "18",
                name: "All-in-One Slim View",
                description: "Design fino e discreto, ótimo para recepções e atendimento ao cliente.",
                price: 2799.99,
                image: "/imagens/computador.png",
            },
            {
                id: "19",
                name: "Notebook Infinity Pro",
                description: "Alta duração de bateria e tela com cores vibrantes.",
                price: 5299.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "20",
                name: "Desktop Essencial",
                description: "O básico para o dia a dia, com preço acessível.",
                price: 1799.99,
                image: "/imagens/computador.png",
            },
            {
                id: "21",
                name: "Notebook MaxPower G8",
                description: "Projetado para tarefas intensas com resfriamento avançado.",
                price: 7499.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "22",
                name: "Mini PC Delta Core",
                description: "Eficiente em consumo e excelente para automações.",
                price: 1999.00,
                image: "/imagens/computador.png",
            },
            {
                id: "23",
                name: "Notebook ZenTech",
                description: "Design sóbrio com hardware silencioso.",
                price: 3499.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "24",
                name: "Desktop Versatile",
                description: "Versátil para uso comercial e educacional.",
                price: 2699.99,
                image: "/imagens/computador.png",
            },
            {
                id: "25",
                name: "Notebook AlphaBook 360",
                description: "Conversível com tela dobrável e caneta touch.",
                price: 5899.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "26",
                name: "PC Gamer Lightning X",
                description: "Performance para eSports com taxa alta de FPS.",
                price: 8299.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "27",
                name: "All-in-One Visionary",
                description: "Ideal para designers e artistas visuais.",
                price: 4999.99,
                image: "/imagens/computador.png",
            },
            {
                id: "28",
                name: "Notebook Lightbook",
                description: "Portátil e eficiente para quem vive em movimento.",
                price: 2899.99,
                image: "/imagens/notebook.png",
            },
            {
                id: "29",
                name: "Desktop MegaOffice",
                description: "Configuração ideal para empresas de médio porte.",
                price: 4599.99,
                image: "/imagens/computador.png",
            },
            {
                id: "30",
                name: "Notebook Expresso S3",
                description: "Rápido, compacto e com ótimo custo-benefício.",
                price: 2199.99,
                image: "/imagens/notebook.png",
            }
        ],        
        mouse: [
            {
                id: "5",
                name: "Mouse Óptico G-Tech",
                description: "Mouse ergonômico, ideal para longas sessões de trabalho ou jogos.",
                price: 129.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "6",
                name: "Mouse Gamer Z-Force",
                description: "Mouse gamer com 7 botões programáveis e luz RGB.",
                price: 249.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "7",
                name: "Mouse Wireless TechX",
                description: "Mouse sem fio com alta precisão e design moderno.",
                price: 99.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "8",
                name: "Mouse Ultralight Speedster",
                description: "Mouse ultraleve com sensor de alta performance.",
                price: 199.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "9",
                name: "Mouse Compact Clicker",
                description: "Modelo compacto ideal para viagens e mobilidade.",
                price: 69.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "10",
                name: "Mouse RGB Phantom",
                description: "Mouse com iluminação RGB dinâmica e ajuste de DPI.",
                price: 159.90,
                image: "/imagens/mouse.png",
            },
            {
                id: "11",
                name: "Mouse Precision X",
                description: "Alta precisão com 12.000 DPI para gamers exigentes.",
                price: 299.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "12",
                name: "Mouse Econômico BasicM",
                description: "Modelo simples e funcional para uso diário.",
                price: 39.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "13",
                name: "Mouse Bluetooth Swift",
                description: "Conexão via Bluetooth com longa duração de bateria.",
                price: 119.90,
                image: "/imagens/mouse.png",
            },
            {
                id: "14",
                name: "Mouse Vertikal Pro",
                description: "Design vertical que reduz tensão no pulso.",
                price: 189.00,
                image: "/imagens/mouse.png",
            },
            {
                id: "15",
                name: "Mouse Gamer X-Treme",
                description: "Modelo gamer com macro-programação e sensor ótico de elite.",
                price: 279.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "16",
                name: "Mouse Wireless Touch",
                description: "Superfície sensível ao toque e conexão rápida.",
                price: 149.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "17",
                name: "Mouse Classic Pro",
                description: "Design tradicional com durabilidade estendida.",
                price: 59.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "18",
                name: "Mouse Dual Mode",
                description: "Funciona com ou sem fio, ideal para quem gosta de versatilidade.",
                price: 179.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "19",
                name: "Mouse Gamer Dragoon",
                description: "Sensor de 16000 DPI e grip lateral texturizado.",
                price: 319.90,
                image: "/imagens/mouse.png",
            },
            {
                id: "20",
                name: "Mouse UltraSilence",
                description: "Cliques silenciosos, ideal para ambientes de estudo e trabalho.",
                price: 89.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "21",
                name: "Mouse RGB Nebula",
                description: "Iluminação RGB em padrão nebulosa com sincronização de efeitos.",
                price: 169.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "22",
                name: "Mouse TechSlim",
                description: "Design fino com ótimo encaixe para mãos pequenas.",
                price: 109.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "23",
                name: "Mouse Gamer BeastMode",
                description: "Botões laterais personalizáveis e acabamento premium.",
                price: 349.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "24",
                name: "Mouse Portátil ClickMini",
                description: "Ideal para notebooks, fácil de transportar.",
                price: 79.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "25",
                name: "Mouse Silent Glide",
                description: "Super silencioso com sensor ótico de precisão.",
                price: 129.90,
                image: "/imagens/mouse.png",
            },
            {
                id: "26",
                name: "Mouse Wireless GO",
                description: "Conectividade rápida e corpo resistente.",
                price: 99.00,
                image: "/imagens/mouse.png",
            },
            {
                id: "27",
                name: "Mouse Gamer Legend",
                description: "Performance profissional para campeonatos.",
                price: 399.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "28",
                name: "Mouse Comfort Touch",
                description: "Textura macia com apoio para o dedo anelar.",
                price: 139.90,
                image: "/imagens/mouse.png",
            },
            {
                id: "29",
                name: "Mouse DualSensor",
                description: "Com dois sensores para maior precisão em jogos competitivos.",
                price: 269.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "30",
                name: "Mouse Optical Wave",
                description: "Ergonômico e com design moderno em cores vibrantes.",
                price: 119.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "31",
                name: "Mouse Elite Performance",
                description: "Para quem busca velocidade, precisão e durabilidade.",
                price: 289.99,
                image: "/imagens/mouse.png",
            },
            {
                id: "32",
                name: "Mouse Gamer Vulcano",
                description: "Sensor infravermelho com resposta instantânea.",
                price: 189.90,
                image: "/imagens/mouse.png",
            },
            {
                id: "33",
                name: "Mouse Ergofit",
                description: "Feito para conforto prolongado em ambientes de escritório.",
                price: 149.00,
                image: "/imagens/mouse.png",
            },
            {
                id: "34",
                name: "Mouse Lightning RGB",
                description: "Efeitos de luz em cascata com ajuste dinâmico.",
                price: 199.99,
                image: "/imagens/mouse.png",
            }
        ],        
        headset: [
            {
                id: "8",
                name: "Headset Pro Sound",
                description: "Fone de ouvido com microfone, ideal para streamers e gamers.",
                price: 299.99,
                image: "/imagens/headset.png",
            },
            {
                id: "9",
                name: "Headset Gaming X",
                description: "Headset com som surround 7.1, ideal para uma experiência imersiva.",
                price: 349.99,
                image: "/imagens/headset.png",
            },
            {
                id: "10",
                name: "Fone de Ouvido Bluetooth Elite",
                description: "Fone Bluetooth com cancelamento de ruído e bateria de longa duração.",
                price: 399.99,
                image: "/imagens/headset.png",
            },
            {
                id: "11",
                name: "Headset Wireless Thunder",
                description: "Headset sem fio com excelente qualidade de som e microfone removível.",
                price: 259.99,
                image: "/imagens/headset.png",
            },
            {
                id: "12",
                name: "Headset Gamer Titan",
                description: "Com som de alta definição e microfone com cancelamento de ruído.",
                price: 449.99,
                image: "/imagens/headset.png",
            },
            {
                id: "13",
                name: "Headset NoiseCanceler 360",
                description: "Fones de ouvido com cancelamento ativo de ruído e ajuste preciso.",
                price: 499.99,
                image: "/imagens/headset.png",
            },
            {
                id: "14",
                name: "Headset UltraSound",
                description: "Fones com som ultra nítido e alto desempenho em jogos e músicas.",
                price: 319.99,
                image: "/imagens/headset.png",
            },
            {
                id: "15",
                name: "Fone de Ouvido Comfort Pro",
                description: "Fone com almofadas de memória para maior conforto e durabilidade.",
                price: 189.99,
                image: "/imagens/headset.png",
            },
            {
                id: "16",
                name: "Headset Bluetooth Flex",
                description: "Modelo sem fio, ideal para quem gosta de mobilidade e conforto.",
                price: 139.99,
                image: "/imagens/headset.png",
            },
            {
                id: "17",
                name: "Headset HyperGaming 7.1",
                description: "Headset com som surround 7.1 e microfone ajustável.",
                price: 369.99,
                image: "/imagens/headset.png",
            },
            {
                id: "18",
                name: "Fone de Ouvido StudioMax",
                description: "Fone de estúdio com excelente qualidade de áudio para profissionais.",
                price: 799.99,
                image: "/imagens/headset.png",
            },
            {
                id: "19",
                name: "Headset Wireless Aero",
                description: "Headset sem fio com som surround e bateria de até 20 horas.",
                price: 319.99,
                image: "/imagens/headset.png",
            },
            {
                id: "20",
                name: "Headset Gamer ProPlus",
                description: "Com áudio 3D e microfone retrátil com filtro de ruídos.",
                price: 349.99,
                image: "/imagens/headset.png",
            },
            {
                id: "21",
                name: "Headset LightWave",
                description: "Design leve e confortável com luzes RGB ajustáveis.",
                price: 229.99,
                image: "/imagens/headset.png",
            },
            {
                id: "22",
                name: "Headset ComfortSound",
                description: "Headset com ajuste de pressão e conforto para uso prolongado.",
                price: 159.99,
                image: "/imagens/headset.png",
            },
            {
                id: "23",
                name: "Headset Quantum Wireless",
                description: "Tecnologia sem fio com áudio de 7.1 para jogadores competitivos.",
                price: 429.99,
                image: "/imagens/headset.png",
            },
            {
                id: "24",
                name: "Headset StormX",
                description: "Com microfone de alta definição e drivers de 50mm.",
                price: 259.99,
                image: "/imagens/headset.png",
            },
            {
                id: "25",
                name: "Headset Elite Pro",
                description: "Fones de ouvido com som cristalino e microfone de cancelamento de ruído.",
                price: 499.99,
                image: "/imagens/headset.png",
            },
            {
                id: "26",
                name: "Headset EcoSound",
                description: "Fones ecológicos feitos com materiais reciclados e som natural.",
                price: 199.99,
                image: "/imagens/headset.png",
            },
            {
                id: "27",
                name: "Fone de Ouvido Xtreme Bass",
                description: "Com graves potentes e som balanceado para música e jogos.",
                price: 139.99,
                image: "/imagens/headset.png",
            },
            {
                id: "28",
                name: "Headset DualSound",
                description: "Com ajuste duplo de som para diferentes tipos de conteúdo (jogos, música, filmes).",
                price: 289.99,
                image: "/imagens/headset.png",
            },
            {
                id: "29",
                name: "Headset VRMax",
                description: "Fone com som espacial, ideal para jogos de realidade virtual.",
                price: 349.90,
                image: "/imagens/headset.png",
            },
            {
                id: "30",
                name: "Fone de Ouvido AeroSound",
                description: "Leve, com excelente desempenho de som e microfone retrátil.",
                price: 159.99,
                image: "/imagens/headset.png",
            },
            {
                id: "31",
                name: "Headset Titanium Sound",
                description: "Com som imersivo e microfone com tecnologia anti-ruído.",
                price: 369.99,
                image: "/imagens/headset.png",
            },
            {
                id: "32",
                name: "Fone de Ouvido ComfortSound Pro",
                description: "Almofadas confortáveis e som natural para longas sessões de uso.",
                price: 229.99,
                image: "/imagens/headset.png",
            },
            {
                id: "33",
                name: "Headset Sonic Pro",
                description: "Com microfone de alto desempenho e drivers de 50mm para qualidade de som.",
                price: 289.99,
                image: "/imagens/headset.png",
            },
            {
                id: "34",
                name: "Headset AeroGaming",
                description: "Com áudio de 7.1 e microfone com tecnologia anti-eco.",
                price: 449.99,
                image: "/imagens/headset.png",
            }
        ],        
        teclado: [
            {
                id: "11",
                name: "Teclado Mecânico XTech",
                description: "Teclado mecânico com switches azuis, ideal para gamers.",
                price: 499.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "12",
                name: "Teclado Multimídia MK-120",
                description: "Teclado sem fio com design ergonômico e teclas silenciosas.",
                price: 159.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "13",
                name: "Teclado Gamer ThunderPro",
                description: "Teclado gamer com retroiluminação RGB e switches mecânicos rápidos.",
                price: 599.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "14",
                name: "Teclado Mecânico HyperX",
                description: "Teclado mecânico com switches lineares e iluminação personalizável.",
                price: 499.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "15",
                name: "Teclado Wireless TechPro",
                description: "Teclado sem fio com design compacto e teclas responsivas.",
                price: 219.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "16",
                name: "Teclado Gamer Xtreme",
                description: "Teclado mecânico com switches táteis e iluminação RGB.",
                price: 379.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "17",
                name: "Teclado Multifuncional TurboTech",
                description: "Teclado com teclas programáveis e suporte a macros.",
                price: 269.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "18",
                name: "Teclado Compacto SlimPro",
                description: "Teclado slim e compacto, ideal para quem tem pouco espaço.",
                price: 139.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "19",
                name: "Teclado RGB StormForce",
                description: "Teclado com retroiluminação RGB e switches mecânicos rápidos.",
                price: 459.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "20",
                name: "Teclado Multimídia Comfort",
                description: "Teclado com design ergonômico e teclas de baixo perfil.",
                price: 179.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "21",
                name: "Teclado Mechanical Pro",
                description: "Teclado mecânico com switches dourados e iluminação RGB.",
                price: 599.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "22",
                name: "Teclado Bluetooth Flex",
                description: "Teclado Bluetooth sem fio com teclas silenciosas e compactas.",
                price: 229.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "23",
                name: "Teclado Gamer Z-Strike",
                description: "Teclado com retroiluminação RGB e teclas anti-ghosting.",
                price: 349.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "24",
                name: "Teclado Ergonomico ProPlus",
                description: "Teclado com suporte ergonômico para reduzir a fadiga nas mãos.",
                price: 299.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "25",
                name: "Teclado Mecânico Titan",
                description: "Teclado com switches mecânicos lineares e iluminação LED personalizável.",
                price: 529.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "26",
                name: "Teclado Ultra Compact",
                description: "Teclado compactado e leve, ideal para transporte.",
                price: 169.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "27",
                name: "Teclado USB StormX",
                description: "Teclado com entrada USB e teclas macias para digitação rápida.",
                price: 149.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "28",
                name: "Teclado Retro RGB",
                description: "Teclado mecânico com retroiluminação RGB e layout personalizado.",
                price: 399.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "29",
                name: "Teclado SlimTech",
                description: "Teclado slim com teclas de baixo perfil e alta durabilidade.",
                price: 199.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "30",
                name: "Teclado Pro RGB Ultimate",
                description: "Teclado mecânico com switches táteis e iluminação RGB ajustável.",
                price: 649.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "31",
                name: "Teclado Wireless SmartKey",
                description: "Teclado sem fio com bateria de longa duração e teclas silenciosas.",
                price: 209.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "32",
                name: "Teclado LED Pro",
                description: "Teclado mecânico com LEDs multicoloridos e teclas de resposta rápida.",
                price: 559.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "33",
                name: "Teclado Gamer X1 Pro",
                description: "Teclado gamer com switches mecânicos e iluminação LED personalizável.",
                price: 499.99,
                image: "/imagens/teclado.png",
            },
            {
                id: "34",
                name: "Teclado Multimídia 360",
                description: "Teclado sem fio com teclas multimídia e design ergonômico.",
                price: 179.99,
                image: "/imagens/teclado.png",
            }
        ],
        
        celular: [
            {
                id: "14",
                name: "Celular Smartphone Z2",
                description: "Smartphone com tela de 6.5' e câmera de 48MP, ideal para fotos e vídeos.",
                price: 2499.99,
                image: "/imagens/celular.png",
            },
            {
                id: "15",
                name: "Celular Smartphone Ultra X10",
                description: "Celular com tela de 6.8' OLED, 128GB de armazenamento e câmera de 64MP.",
                price: 3499.99,
                image: "/imagens/celular.png",
            },
            {
                id: "16",
                name: "Celular Smartphone Compact Z1",
                description: "Celular compacto com excelente custo-benefício, ideal para quem procura praticidade.",
                price: 1599.99,
                image: "/imagens/celular.png",
            },
            {
                id: "17",
                name: "Celular Premium X9",
                description: "Celular topo de linha com processador Snapdragon, 12GB de RAM e câmera profissional.",
                price: 4499.99,
                image: "/imagens/celular.png",
            },
            {
                id: "18",
                name: "Celular Smartphone Max Z6",
                description: "Smartphone com tela de 6.7' AMOLED, 128GB de armazenamento e 5G.",
                price: 3199.99,
                image: "/imagens/celular.png",
            },
            {
                id: "19",
                name: "Celular Smartphone X3 Pro",
                description: "Celular com tela de 6.4', câmera tripla de 64MP, ideal para capturar todos os momentos.",
                price: 2899.99,
                image: "/imagens/celular.png",
            },
            {
                id: "20",
                name: "Celular Pocket Z1",
                description: "Smartphone compacto e acessível, com 4GB de RAM e 64GB de armazenamento.",
                price: 1299.99,
                image: "/imagens/celular.png",
            },
            {
                id: "21",
                name: "Celular Galaxy M20",
                description: "Celular com tela de 6.5' e câmera de 48MP, ideal para entretenimento.",
                price: 2499.99,
                image: "/imagens/celular.png",
            },
            {
                id: "22",
                name: "Celular Galaxy S10 Ultra",
                description: "Smartphone premium com tela de 6.9', câmera de 108MP e 256GB de armazenamento.",
                price: 4999.99,
                image: "/imagens/celular.png",
            },
            {
                id: "23",
                name: "Celular Nano Mini 6",
                description: "Smartphone mini com 4.7' de tela, ideal para quem busca portabilidade.",
                price: 999.99,
                image: "/imagens/celular.png",
            },
            {
                id: "24",
                name: "Celular Fast Pro 5G",
                description: "Celular com tela de 6.8' OLED, 8GB de RAM e suporte a 5G.",
                price: 3999.99,
                image: "/imagens/celular.png",
            },
            {
                id: "25",
                name: "Celular Z3 Plus",
                description: "Celular com 6.5' de tela, processador Octa-Core e câmera de 48MP.",
                price: 2599.99,
                image: "/imagens/celular.png",
            },
            {
                id: "26",
                name: "Celular MiniPhone 3",
                description: "Celular compacto, ideal para chamadas e mensagens.",
                price: 799.99,
                image: "/imagens/celular.png",
            },
            {
                id: "27",
                name: "Celular Max Z10",
                description: "Celular com 6.9' de tela, processador 5G e 256GB de armazenamento.",
                price: 4299.99,
                image: "/imagens/celular.png",
            },
            {
                id: "28",
                name: "Celular Mobile Z Pro",
                description: "Celular com tela de 6.7', câmeras de 64MP e 128GB de armazenamento.",
                price: 3799.99,
                image: "/imagens/celular.png",
            },
            {
                id: "29",
                name: "Celular Flip Tech Z2",
                description: "Celular flip com tela dobrável de 6.5' e câmera de 48MP.",
                price: 5499.99,
                image: "/imagens/celular.png",
            },
            {
                id: "30",
                name: "Celular Speed 5G",
                description: "Smartphone com 5G, tela de 6.4' e 128GB de armazenamento.",
                price: 2899.99,
                image: "/imagens/celular.png",
            },
            {
                id: "31",
                name: "Celular Ultra Max X5",
                description: "Celular de 6.7', 8GB de RAM e câmeras com ultra zoom de 100MP.",
                price: 4399.99,
                image: "/imagens/celular.png",
            },
            {
                id: "32",
                name: "Celular Vision Pro X8",
                description: "Celular com tela OLED de 6.8' e 128GB de armazenamento.",
                price: 3599.99,
                image: "/imagens/celular.png",
            },
            {
                id: "33",
                name: "Celular Zen Lite",
                description: "Smartphone básico com 5.5' de tela, 2GB de RAM e 16GB de armazenamento.",
                price: 599.99,
                image: "/imagens/celular.png",
            },
            {
                id: "34",
                name: "Celular Premium Z Ultra",
                description: "Smartphone com 6.9' de tela, 12GB de RAM e 512GB de armazenamento.",
                price: 5999.99,
                image: "/imagens/celular.png",
            },
            {
                id: "35",
                name: "Celular Echo X10",
                description: "Celular com 6.5' de tela, processador octa-core e câmeras de 64MP.",
                price: 3199.99,
                image: "/imagens/celular.png",
            },
            {
                id: "36",
                name: "Celular Econo Z7",
                description: "Smartphone de entrada com 5.0' de tela e 1GB de RAM.",
                price: 499.99,
                image: "/imagens/celular.png",
            },
            {
                id: "37",
                name: "Celular Smart Edge 3",
                description: "Celular com 6.4' de tela, câmera de 48MP e 64GB de armazenamento.",
                price: 1699.99,
                image: "/imagens/celular.png",
            },
            {
                id: "38",
                name: "Celular Nova Edge X5",
                description: "Smartphone com 6.8' de tela e câmera de 64MP, ideal para jogos e entretenimento.",
                price: 3899.99,
                image: "/imagens/celular.png",
            }
        ],
        
    };

    // Verifica a query e retorna os produtos simulados correspondentes
    const produtosFiltrados = produtosMock[query.toLowerCase()] || [];
    
    return produtosFiltrados;
}

export default fetchProducts;
